options(max.print=1000000)
print(getwd())
data <- read.csv("heart.txt")
print(data)
print(is.data.frame(data))
print(nrow(data))
print(ncol(data))

install.packages("corrplot")
M<-cor(data)
#head(round(M,2))
round(M,2)
library(corrplot)
corrplot(M, method="number", type="lower")
